extraction:
  cpp:
    after_prepare: 
      - python report.py 12
  cobol:
    after_prepare: 
      - python report.py 12
  csharp:
    after_prepare: 
      - python report.py 12
  java:
    after_prepare: 
      - python report.py 12
  javascript:
    after_prepare: 
      - python report.py 12
  python:
    after_prepare: 
      - python report.py 12
